name: Continuous Integration for Rasa
on: [pull_request]
jobs: 
  training-testing:
    name: Training and Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m ensurepip --upgrade
          pip install -r requirements.txt
      
      - name: Cross-validate NLU model
        id: cvnlu
        run: |
          rasa --version
          rasa test nlu -f 3 --croess-validation 
          python .github/worklows/format_results.py
      
      - name: post cross-val results to PR
        if: steps.cvnlu.outcome == 'success'
        uses: amn41/comment-on-pr@comment-file-contents
        continue-on-error: true
        with:
          msg: results.md
      
      - name: Train model
        run: |
          rasa train --quiet
          
      - name: Test end to end stories
        run: |
         rasa test core --fail-on-prediction-errors
          
